# Generated by Django 3.1.14 on 2023-05-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Дата время создания записи')),
                ('start_at', models.DateTimeField(null=True, verbose_name='Начало сеанса')),
                ('end_at', models.DateTimeField(null=True, verbose_name='Окончание сеанса')),
                ('price', models.FloatField(null=True, verbose_name='Стоимость услуги')),
                ('deliver', models.BooleanField(null=True, verbose_name='Услуга оказана')),
                ('tentatively', models.BooleanField(null=True, verbose_name='Предварительная запись')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='appadmin.customer', verbose_name='Покупатель')),
                ('saloon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='appadmin.beautysaloon', verbose_name='Салон')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='appadmin.serivice', verbose_name='Услуга')),
            ],
        ),
    ]
