# Generated by Django 3.1.14 on 2023-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0004_auto_20230524_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautysaloon',
            name='phonenumber',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона салона'),
        ),
        migrations.AddField(
            model_name='customer',
            name='CHAT_ID',
            field=models.CharField(max_length=20, null=True, verbose_name='идентификатор чата tg с клиентом'),
        ),
    ]
