# Generated by Django 3.1.14 on 2023-05-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0005_auto_20230526_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tentatively',
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='appadmin.employee', verbose_name='Специалист'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Содержимое отзыва')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='appadmin.customer', verbose_name='Покупатель')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='appadmin.employee', verbose_name='Специалист')),
            ],
        ),
    ]
